import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

type SupportedLanguage = 'ja' | 'en' | 'vn';

interface LanguageContextValue {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  toggleLanguage: () => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

const LANGUAGE_ORDER: SupportedLanguage[] = ['ja', 'en', 'vn'];

const translations: Record<SupportedLanguage, Record<string, string>> = {
  ja: {
    'app.title': 'OSマネージャー',
    'app.subtitle': 'エスハイグループ',
    'nav.dashboard': 'ダッシュボード',
    'nav.tracking': '案件トラッキング',
    'nav.totalView': '年間ビュー',
    'nav.signOut': 'サインアウト',
    'header.dashboardTitle': 'ダッシュボード',
    'header.performance': 'パフォーマンス概要',
    'header.exchangeRate': '為替レート (JPY → VND)',
    'search.placeholder': 'プロジェクトを検索...',
    'buttons.export': 'エクスポート',
    'buttons.project': 'プロジェクト',
    'buttons.language.jp': '日本語',
    'buttons.language.en': 'English',
    'buttons.language.vn': 'ベトナム語',
    'app.adminUser': '管理者ユーザー',
    'modals.project.title': '新規プロジェクト',
    'modals.project.code': 'プロジェクトコード',
    'modals.project.name': '名称',
    'modals.project.type': '種別',
    'modals.project.unitPrice': '単価 (JPY)',
    'modals.actions.cancel': 'キャンセル',
    'modals.project.submit': '作成',
    'modals.period.title': '新しい期間',
    'modals.period.year': '年',
    'modals.period.half': '半期',
    'modals.period.option.h1': 'H1 (1月-6月)',
    'modals.period.option.h2': 'H2 (7月-12月)',
    'modals.period.submit': '期間を追加',
    'auth.subtitle': 'ローカルデータ環境',
    'auth.info': 'これはローカルデモ環境です。サーバー接続は不要です。',
    'auth.button': 'アプリを開く',
    'auth.loading': 'システムにアクセス中...',
    'tracker.code': '案件コード',
    'tracker.projectName': '案件名',
    'tracker.unitPrice': '単価 (JPY)',
    'tracker.monthSuffix': '月',
    'tracker.monthSubLabel': '計画 / 実績',
    'tracker.planShort': '計画',
    'tracker.actualShort': '実績',
    'tracker.totalHrsPlan': '合計時間（計画）',
    'tracker.totalHrsActual': '合計時間（実績）',
    'tracker.revenuePlan': '売上（計画）',
    'tracker.revenueActual': '売上（実績）',
    'tracker.noResults': '検索条件に一致するプロジェクトがありません。',
    'dashboard.kpi.totalRevenue': '実績売上高',
    'dashboard.kpi.revenueAchievement': '売上達成率',
    'dashboard.kpi.totalHours': '実績時間',
    'dashboard.kpi.plannedRevenue': '計画売上高',
    'dashboard.kpi.targetLabel': '目標',
    'dashboard.kpi.planLabel': '計画',
    'dashboard.chart.monthly': '月次売上：計画 vs 実績',
    'dashboard.chart.accumulated': '累計売上推移',
    'dashboard.chart.accActual': '累計実績',
    'dashboard.chart.accPlan': '累計計画',
    'dashboard.header.desc': '年度別の進捗と収支を確認',
    'dashboard.fx.label': '為替レート',
    'dashboard.fx.hourly': '時給 (JPY)',
    'dashboard.license.count': 'ライセンス台数',
    'dashboard.license.perSeat': '1台あたり (JPY)',
    'dashboard.license.total': '年間ライセンス費',
    'dashboard.kpi.planHoursLabel': '計画工数',
    'dashboard.kpi.actualHoursLabel': '実績工数',
    'dashboard.kpi.achievementLabel': '達成率',
    'dashboard.kpi.unitPriceLabel': '標準単価',
    'dashboard.kpi.remainingLabel': '残工数',
    'dashboard.license.card.title': 'CADライセンス管理',
    'dashboard.license.card.subtitle': '年間ライセンス費',
    'dashboard.license.card.costPerHour': 'コスト/時 (計画)',
    'dashboard.gross.plan': '総売上（計画）',
    'dashboard.gross.actual': '総売上（実績）',
    'dashboard.net.plan': '純売上（計画）',
    'dashboard.net.actual': '純売上（実績）',
    'dashboard.net.margin': '利益率',
    'dashboard.costAnalysis.title': 'コスト分析',
    'dashboard.costAnalysis.subtitle': 'ライセンス影響を把握',
    'dashboard.costAnalysis.licensePerHour': 'ライセンス/時',
    'dashboard.costAnalysis.netRate': '実質時給',
    'dashboard.costAnalysis.breakEven': '損益分岐工数',
    'dashboard.charts.cumulative': '累計売上（計画 vs 実績）',
    'dashboard.summary.title': '財務サマリー',
    'dashboard.summary.gross': '総売上（実績）',
    'dashboard.summary.license': 'ライセンス費',
    'dashboard.summary.net': '純売上（実績）',
    'dashboard.summary.margin': '利益率（実績）',
    'dashboard.empty': 'まだダッシュボードデータがありません。トラッキングデータを入力してください。',
    'project.type.mechanical': '機械設計',
    'project.type.software': 'ソフトウェア開発',
    'project.type.translation': '翻訳',
    'project.type.other': 'その他',
    'alerts.projectCreateError': 'プロジェクトの作成に失敗しました',
    'alerts.exportFailed': 'エクスポートに失敗しました',
    'tracker.select': 'Select',
    'tracker.selectAll': 'Select All',
    'tracker.clearSelection': 'Clear Selection',
    'tracker.deleteSelected': 'Delete Selected',
    'tracker.deleteSingle': 'Delete',
    'tracker.selectedLabel': 'Selected',
    'tracker.confirmDeleteOne': 'Delete project "{name}"? This removes its records.',
    'tracker.confirmDeleteMany': 'Delete {count} projects and their records?',
    'dashboard.kpi.yearTotal': '年度合計',
    'dashboard.license.units': '台',
    'dashboard.license.targetPc': '対象PC',
    'dashboard.notes.allocatePlan': '計画工数で按分',
    'dashboard.notes.unitMinusLicense': '単価 - ライセンス/時',
    'dashboard.notes.breakEven': 'ライセンス費 ÷ 単価',
    'dashboard.perHour': ' / 時',
    'totalView.chartTitle': '年間概要',
    'totalView.axis.monthlyHours': '月間工数',
    'totalView.axis.accumulated': '累計',
    'totalView.tableHeader.type': '種別',
    'totalView.tableHeader.total': '合計',
  },
  en: {
    'app.title': 'OS Manager',
    'app.subtitle': 'Esuhai Group',
    'nav.dashboard': 'Dashboard',
    'nav.tracking': 'Project Tracking',
    'nav.totalView': 'Yearly View',
    'nav.signOut': 'Sign Out',
    'header.dashboardTitle': 'Dashboard',
    'header.performance': 'Performance Overview',
    'header.exchangeRate': 'Exchange Rate (JPY → VND)',
    'search.placeholder': 'Search projects...',
    'buttons.export': 'Export',
    'buttons.project': 'Project',
    'buttons.language.jp': 'Japanese',
    'buttons.language.en': 'English',
    'buttons.language.vn': 'Vietnamese',
    'app.adminUser': 'Admin User',
    'modals.project.title': 'Add New Project',
    'modals.project.code': 'Project Code',
    'modals.project.name': 'Name',
    'modals.project.type': 'Type',
    'modals.project.unitPrice': 'Unit Price (JPY)',
    'modals.actions.cancel': 'Cancel',
    'modals.project.submit': 'Create Project',
    'modals.period.title': 'New Period',
    'modals.period.year': 'Year',
    'modals.period.half': 'Half',
    'modals.period.option.h1': 'H1 (Jan-Jun)',
    'modals.period.option.h2': 'H2 (Jul-Dec)',
    'modals.period.submit': 'Add Period',
    'auth.subtitle': 'Local Data Environment',
    'auth.info': 'This is a local demonstration version. No server connection required.',
    'auth.button': 'Enter Application',
    'auth.loading': 'Accessing System...',
    'tracker.code': 'Project Code',
    'tracker.projectName': 'Project Name',
    'tracker.unitPrice': 'Unit Price (JPY)',
    'tracker.monthSuffix': ' Month',
    'tracker.monthSubLabel': 'Plan / Actual',
    'tracker.planShort': 'Plan',
    'tracker.actualShort': 'Actual',
    'tracker.totalHrsPlan': 'Total Hours (Plan)',
    'tracker.totalHrsActual': 'Total Hours (Actual)',
    'tracker.revenuePlan': 'Revenue (Plan)',
    'tracker.revenueActual': 'Revenue (Actual)',
    'tracker.noResults': 'No projects found matching your search.',
    'dashboard.kpi.totalRevenue': 'Total Revenue (Actual)',
    'dashboard.kpi.revenueAchievement': 'Revenue Achievement',
    'dashboard.kpi.totalHours': 'Total Hours',
    'dashboard.kpi.plannedRevenue': 'Planned Revenue',
    'dashboard.kpi.targetLabel': 'Target',
    'dashboard.kpi.planLabel': 'Plan',
    'dashboard.chart.monthly': 'Monthly Revenue: Plan vs Actual',
    'dashboard.chart.accumulated': 'Accumulated Revenue Trend',
    'dashboard.chart.accActual': 'Accumulated Actual',
    'dashboard.chart.accPlan': 'Accumulated Plan',
    'dashboard.header.desc': 'Review progress and revenue by year',
    'dashboard.fx.label': 'Exchange Rate',
    'dashboard.fx.hourly': 'Hourly Rate (JPY)',
    'dashboard.license.count': 'License Seats',
    'dashboard.license.perSeat': 'Fee per Seat (JPY)',
    'dashboard.license.total': 'Annual License Cost',
    'dashboard.kpi.planHoursLabel': 'Planned Hours',
    'dashboard.kpi.actualHoursLabel': 'Actual Hours',
    'dashboard.kpi.achievementLabel': 'Achievement',
    'dashboard.kpi.unitPriceLabel': 'Unit Rate',
    'dashboard.kpi.remainingLabel': 'Remaining Hours',
    'dashboard.license.card.title': 'CAD License Management',
    'dashboard.license.card.subtitle': 'Annual License Fee',
    'dashboard.license.card.costPerHour': 'Cost per Hour (plan)',
    'dashboard.gross.plan': 'Gross Revenue (Plan)',
    'dashboard.gross.actual': 'Gross Revenue (Actual)',
    'dashboard.net.plan': 'Net Revenue (Plan)',
    'dashboard.net.actual': 'Net Revenue (Actual)',
    'dashboard.net.margin': 'Profit Margin',
    'dashboard.costAnalysis.title': 'Cost Analysis',
    'dashboard.costAnalysis.subtitle': 'Understand license impact',
    'dashboard.costAnalysis.licensePerHour': 'License / Hour',
    'dashboard.costAnalysis.netRate': 'Net Hourly Rate',
    'dashboard.costAnalysis.breakEven': 'Break-even Hours',
    'dashboard.charts.cumulative': 'Cumulative Revenue (Plan vs Actual)',
    'dashboard.summary.title': 'Financial Summary',
    'dashboard.summary.gross': 'Gross (Actual)',
    'dashboard.summary.license': 'License Cost',
    'dashboard.summary.net': 'Net (Actual)',
    'dashboard.summary.margin': 'Margin (Actual)',
    'dashboard.empty': 'No dashboard data available yet. Add tracking records to view analytics.',
    'project.type.mechanical': 'Mechanical Design',
    'project.type.software': 'Software Development',
    'project.type.translation': 'Translation',
    'project.type.other': 'Other',
    'alerts.projectCreateError': 'Error creating project',
    'alerts.exportFailed': 'Export failed',
    'tracker.select': 'Select',
    'tracker.selectAll': 'Select All',
    'tracker.clearSelection': 'Clear Selection',
    'tracker.deleteSelected': 'Delete Selected',
    'tracker.deleteSingle': 'Delete',
    'tracker.selectedLabel': 'Selected',
    'tracker.confirmDeleteOne': 'Delete project "{name}"? This removes its records.',
    'tracker.confirmDeleteMany': 'Delete {count} projects and their records?',
    'dashboard.kpi.yearTotal': 'Year Total',
    'dashboard.license.units': 'units',
    'dashboard.license.targetPc': 'Target PCs',
    'dashboard.notes.allocatePlan': 'Allocated over planned hours',
    'dashboard.notes.unitMinusLicense': 'Unit rate - license/hour',
    'dashboard.notes.breakEven': 'License cost ÷ unit rate',
    'dashboard.perHour': ' / hour',
    'totalView.chartTitle': 'Yearly Overview',
    'totalView.axis.monthlyHours': 'Monthly Hours',
    'totalView.axis.accumulated': 'Accumulated',
    'totalView.tableHeader.type': 'Type',
    'totalView.tableHeader.total': 'Total',
  },
  vn: {
    'app.title': 'Hệ thống quản lý OS',
    'app.subtitle': 'Tập đoàn Esuhai',
    'nav.dashboard': 'Bảng điều khiển',
    'nav.tracking': 'Theo dõi dự án',
    'nav.totalView': 'Xem theo năm',
    'nav.signOut': 'Đăng xuất',
    'header.dashboardTitle': 'Bảng điều khiển',
    'header.performance': 'Tổng quan hiệu suất',
    'header.exchangeRate': 'Tỷ giá (JPY → VND)',
    'search.placeholder': 'Tìm kiếm dự án...',
    'buttons.export': 'Xuất',
    'buttons.project': 'Dự án',
    'buttons.language.jp': 'Tiếng Nhật',
    'buttons.language.en': 'Tiếng Anh',
    'buttons.language.vn': 'Tiếng Việt',
    'app.adminUser': 'Quản trị viên',
    'modals.project.title': 'Thêm dự án mới',
    'modals.project.code': 'Mã dự án',
    'modals.project.name': 'Tên',
    'modals.project.type': 'Loại',
    'modals.project.unitPrice': 'Đơn giá (JPY)',
    'modals.actions.cancel': 'Hủy',
    'modals.project.submit': 'Tạo dự án',
    'modals.period.title': 'Kỳ mới',
    'modals.period.year': 'Năm',
    'modals.period.half': 'Nửa kỳ',
    'modals.period.option.h1': 'H1 (Thg 1-6)',
    'modals.period.option.h2': 'H2 (Thg 7-12)',
    'modals.period.submit': 'Thêm kỳ',
    'auth.subtitle': 'Môi trường dữ liệu cục bộ',
    'auth.info': 'Đây là bản demo cục bộ, không cần kết nối máy chủ.',
    'auth.button': 'Truy cập ứng dụng',
    'auth.loading': 'Đang truy cập hệ thống...',
    'tracker.code': 'Mã dự án',
    'tracker.projectName': 'Tên dự án',
    'tracker.unitPrice': 'Đơn giá (JPY)',
    'tracker.monthSuffix': ' Tháng',
    'tracker.monthSubLabel': 'Kế hoạch / Thực tế',
    'tracker.planShort': 'Kế hoạch',
    'tracker.actualShort': 'Thực tế',
    'tracker.totalHrsPlan': 'Tổng giờ (KH)',
    'tracker.totalHrsActual': 'Tổng giờ (TT)',
    'tracker.revenuePlan': 'Doanh thu (KH)',
    'tracker.revenueActual': 'Doanh thu (TT)',
    'tracker.noResults': 'Không tìm thấy dự án phù hợp.',
    'dashboard.kpi.totalRevenue': 'Tổng doanh thu (Thực tế)',
    'dashboard.kpi.revenueAchievement': 'Tỷ lệ hoàn thành doanh thu',
    'dashboard.kpi.totalHours': 'Tổng giờ',
    'dashboard.kpi.plannedRevenue': 'Doanh thu kế hoạch',
    'dashboard.kpi.targetLabel': 'Mục tiêu',
    'dashboard.kpi.planLabel': 'Kế hoạch',
    'dashboard.chart.monthly': 'Doanh thu hàng tháng: KH vs TT',
    'dashboard.chart.accumulated': 'Xu hướng doanh thu lũy kế',
    'dashboard.chart.accActual': 'Lũy kế thực tế',
    'dashboard.chart.accPlan': 'Lũy kế kế hoạch',
    'dashboard.header.desc': 'Xem tiến độ và doanh thu theo năm',
    'dashboard.fx.label': 'Tỷ giá',
    'dashboard.fx.hourly': 'Đơn giá giờ (JPY)',
    'dashboard.license.count': 'Số máy bản quyền',
    'dashboard.license.perSeat': 'Phí mỗi máy (JPY)',
    'dashboard.license.total': 'Chi phí bản quyền năm',
    'dashboard.kpi.planHoursLabel': 'Giờ kế hoạch',
    'dashboard.kpi.actualHoursLabel': 'Giờ thực tế',
    'dashboard.kpi.achievementLabel': 'Hoàn thành',
    'dashboard.kpi.unitPriceLabel': 'Đơn giá giờ',
    'dashboard.kpi.remainingLabel': 'Giờ còn lại',
    'dashboard.license.card.title': 'Quản lý bản quyền CAD',
    'dashboard.license.card.subtitle': 'Phí bản quyền hằng năm',
    'dashboard.license.card.costPerHour': 'Chi phí/giờ (kế hoạch)',
    'dashboard.gross.plan': 'Doanh thu gộp (Kế hoạch)',
    'dashboard.gross.actual': 'Doanh thu gộp (Thực tế)',
    'dashboard.net.plan': 'Doanh thu ròng (Kế hoạch)',
    'dashboard.net.actual': 'Doanh thu ròng (Thực tế)',
    'dashboard.net.margin': 'Biên lợi nhuận',
    'dashboard.costAnalysis.title': 'Phân tích chi phí',
    'dashboard.costAnalysis.subtitle': 'Hiểu tác động của bản quyền',
    'dashboard.costAnalysis.licensePerHour': 'Bản quyền / giờ',
    'dashboard.costAnalysis.netRate': 'Đơn giá ròng',
    'dashboard.costAnalysis.breakEven': 'Giờ hòa vốn',
    'dashboard.charts.cumulative': 'Doanh thu lũy kế (KH vs TT)',
    'dashboard.summary.title': 'Tóm tắt tài chính',
    'dashboard.summary.gross': 'Doanh thu gộp (Thực tế)',
    'dashboard.summary.license': 'Chi phí bản quyền',
    'dashboard.summary.net': 'Doanh thu ròng (Thực tế)',
    'dashboard.summary.margin': 'Biên lợi nhuận (Thực tế)',
    'dashboard.empty': 'Chưa có dữ liệu bảng điều khiển. Thêm bản ghi theo dõi để xem phân tích.',
    'project.type.mechanical': 'Thiết kế cơ khí',
    'project.type.software': 'Phát triển phần mềm',
    'project.type.translation': 'Biên dịch',
    'project.type.other': 'Khác',
    'alerts.projectCreateError': 'Lỗi khi tạo dự án',
    'alerts.exportFailed': 'Xuất dữ liệu thất bại',
    'tracker.select': 'Chọn',
    'tracker.selectAll': 'Chọn tất cả',
    'tracker.clearSelection': 'Bỏ chọn',
    'tracker.deleteSelected': 'Xóa đã chọn',
    'tracker.deleteSingle': 'Xóa',
    'tracker.selectedLabel': 'Đã chọn',
    'tracker.confirmDeleteOne': 'Xóa dự án "{name}"? Hành động này sẽ xóa các bản ghi của dự án.',
    'tracker.confirmDeleteMany': 'Xóa {count} dự án và các bản ghi liên quan?',
    'dashboard.kpi.yearTotal': 'Tổng năm',
    'dashboard.license.units': 'máy',
    'dashboard.license.targetPc': 'PC mục tiêu',
    'dashboard.notes.allocatePlan': 'Phân bổ trên giờ kế hoạch',
    'dashboard.notes.unitMinusLicense': 'Đơn giá - bản quyền/giờ',
    'dashboard.notes.breakEven': 'Chi phí bản quyền ÷ đơn giá',
    'dashboard.perHour': ' / giờ',
    'totalView.chartTitle': 'Tổng quan năm',
    'totalView.axis.monthlyHours': 'Giờ hàng tháng',
    'totalView.axis.accumulated': 'Lũy kế',
    'totalView.tableHeader.type': 'Loại',
    'totalView.tableHeader.total': 'Tổng',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<SupportedLanguage>('ja');

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    toggleLanguage: () => setLanguage(prev => {
      const idx = LANGUAGE_ORDER.indexOf(prev);
      return LANGUAGE_ORDER[(idx + 1) % LANGUAGE_ORDER.length];
    }),
    t: (key: string, fallback?: string) => {
      return translations[language][key] ?? translations.en[key] ?? fallback ?? key;
    }
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
