import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type SupportedLanguage = 'ja' | 'en' | 'vn';

export interface LanguageContextValue {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  toggleLanguage: () => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LANGUAGE_STORAGE_KEY = 'app_language';

export const SUPPORTED_LANGUAGES: ReadonlyArray<{ code: SupportedLanguage; label: string; short: string }> = [
  { code: 'ja', label: '日本語', short: 'JA' },
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'vn', label: 'Tiếng Việt', short: 'VN' },
];

const LANGUAGE_ORDER: SupportedLanguage[] = ['ja', 'en', 'vn'];

const isSupportedLanguage = (value: string | null): value is SupportedLanguage =>
  value !== null && (LANGUAGE_ORDER as readonly string[]).includes(value);

const readStoredLanguage = (): SupportedLanguage => {
  try {
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (isSupportedLanguage(stored)) return stored;
  } catch {
    // localStorage can throw (private mode, blocked storage) — fall back to the default.
  }
  return 'ja';
};

const translations: Record<SupportedLanguage, Record<string, string>> = {
  ja: {
    'app.title': 'OSマネージャー',
    'app.subtitle': 'エスハイグループ',
    'nav.dashboard': 'OS業務受託状況',
    'nav.tracking': '案件トラッキング',
    'nav.totalView': 'チャートビュー',
    'nav.yearlyData': '年間データ',
    'nav.signOut': 'サインアウト',
    'header.dashboardTitle': 'OS業務受託状況',
    'header.performance': 'パフォーマンス概要',
    'header.exchangeRate': '為替レート (JPY → VND)',
    'search.placeholder': 'プロジェクトを検索...',
    'buttons.export': 'エクスポート',
    'export.options': 'エクスポートオプション',
    'chartExport.notFound': 'チャートが見つかりません。出力されませんでした',
    'chart.colors': '色変更',
    'chart.customizeColors': 'チャートの色をカスタマイズ',
    'chart.highlightCurrentMonth': '今月を強調表示',
    'chart.thisMonth': '今月',
    'chart.dataCsv': 'データ',
    'chart.field.color': '色',
    'chart.field.alpha': '不透明度',
    'chart.field.text': '文字',
    'chart.field.size': 'サイズ',
    'chart.field.width': '太さ',
    'chart.field.bold': '太字',
    'chart.field.outline': '輪郭',
    'totalView.timeGap': '時間 GAP',
    'totalView.percentGap': '% GAP',
    'chartExport.noChart': '出力対象のチャートが見つかりません',
    'chartExport.notFoundCopy': 'チャートが見つかりません。コピーされませんでした',
    'chartExport.noData': '出力するデータがありません',
    'chartExport.pngFailed': '出力に失敗しました: PNG画像を作成できませんでした',
    'chartExport.done': '出力が完了しました',
    'chartExport.copied': 'クリップボードにコピーしました',
    'chartExport.failed': '出力に失敗しました',
    'chartExport.copyFailed': 'コピーに失敗しました',
    'export.copyImage': '画像をコピー',
    'export.copied': 'コピーしました！',
    'export.savePNG': 'PNGとして保存',
    'export.saveSVG': 'SVGとして保存',
    'export.downloadData': 'データ(Excel/CSV)をダウンロード',
    'buttons.project': 'プロジェクト',
    'buttons.language.jp': '日本語',
    'buttons.language.en': 'English',
    'buttons.language.vn': 'ベトナム語',
    'app.adminUser': '管理者ユーザー',
    'modals.project.title': '新規プロジェクト',
    'modals.project.code': 'プロジェクトコード',
    'modals.project.name': '社名',
    'modals.project.type': '業務内容',
    'modals.project.typePlaceholder': '機構設計',
    'modals.project.software': '使用ソフト',
    'modals.project.softwarePlaceholder': 'AutoCAD',
    'modals.actions.cancel': 'キャンセル',
    'modals.project.submit': '作成',
    'modals.period.title': '新しい期間',
    'modals.period.year': '年',
    'modals.period.half': '半期',
    'modals.period.option.h1': 'H1 (1月-6月)',
    'modals.period.option.h2': 'H2 (7月-12月)',
    'modals.period.submit': '期間を追加',
    'modals.period.subtitle': '新しい期間を作成し、含めるプロジェクトを選択します',
    'modals.period.selectProjects': '既存プロジェクトの選択',
    'modals.period.selectProjectsHint': 'この期間に含める既存のプロジェクトを選択してください',
    'modals.period.noProjects': 'プロジェクトがありません',
    'modals.period.noProjectsHint': '先にプロジェクトを作成してください。',
    'auth.subtitle': 'ローカルデータ環境',
    'auth.info': 'これはローカルデモ環境です。サーバー接続は不要です。',
    'auth.button': 'アプリを開く',
    'auth.loading': 'システムにアクセス中...',
    'tracker.no': 'No.',
    'tracker.reorderFailed': '並び順を保存できませんでした。ページを再読み込みしてください。',
    'tracker.moveFailed': 'プロジェクトを移動できませんでした。ページを再読み込みしてください。',
    'tracker.unsavedKept': '未保存の変更は保持されています。「すべて保存」で保存してください。',
    'tracker.code': 'コード',
    'tracker.exclusionMark': '除外記号',
    'tracker.projectName': '社名',
    'tracker.notes': '補足',
    'tracker.software': '使用ソフト',
    'tracker.businessContent': '業務内容',
    'tracker.type': 'タイプ',
    'tracker.unitPrice': '単価 (JPY)',
    'tracker.actions': 'アクション',
    'tracker.moveUp': '上へ移動',
    'tracker.moveDown': '下へ移動',
    'tracker.monthSuffix': '月',
    'tracker.monthSubLabel': '計画 / 実績',
    'tracker.planShort': '計画',
    'tracker.actualShort': '実績',
    'tracker.totalHrs': '合計時間',
    'tracker.revenue': '売上',
    'tracker.totalHrsPlan': '合計時間（計画）',
    'tracker.totalHrsActual': '合計時間（実績）',
    'tracker.revenuePlan': '売上（計画）',
    'tracker.revenueActual': '売上（実績）',
    'tracker.noResults': '検索条件に一致するプロジェクトがありません。',
    'dashboard.kpi.totalRevenue': '実績売上高',
    'export.kpiSummary': '業績ハイライト (KPI〜ライセンス)',
    'export.costAnalysis': 'コスト分析',
    'export.financialSummary': '財務サマリー',
    'dashboard.kpi.varianceDesc': '実績 - 計画',
    'periodManagement.monthRange.h1': '1月-6月',
    'periodManagement.monthRange.h2': '7月-12月',
    'dashboard.colors.title': 'ダッシュボードの配色をカスタマイズ',
    'dashboard.colors.headingSize': '見出しサイズ',
    'dashboard.colors.reset': '初期値に戻す',
    'dashboard.colors.from': '開始色',
    'dashboard.colors.to': '終了色',
    'dashboard.colors.gradientSuffix': '（グラデーション）',
    'dashboard.colors.cardBorders': 'カードの枠線（単色）',
    'dashboard.colors.chartTitle': 'チャートの色をカスタマイズ',
    'dashboard.colors.button': '色変更',
    'dashboard.summary.netOverGross': '純利益 / 総額',
    'dashboard.kpi.revenueAchievement': '売上達成率',
    'dashboard.kpi.totalHours': '実績時間',
    'dashboard.kpi.plannedRevenue': '計画売上高',
    'dashboard.kpi.targetLabel': '目標',
    'dashboard.kpi.planLabel': '計画',
    'dashboard.chart.monthly': '月次売上：計画 vs 実績',
    'dashboard.chart.accumulated': '累計売上推移',
    'dashboard.chart.accActual': '累計実績',
    'dashboard.chart.accPlan': '累計計画',
    'dashboard.header.desc': '年度別の進捗と収支を確認',
    'dashboard.fx.label': '為替レート',
    'dashboard.fx.hourly': '時給 (JPY)',
    'dashboard.license.count': 'ライセンス台数',
    'dashboard.license.perSeat': '1台あたり (JPY)',
    'dashboard.license.total': '年間ライセンス費',
    'dashboard.kpi.planHoursLabel': '計画工数',
    'dashboard.kpi.actualHoursLabel': '実績工数',
    'dashboard.kpi.achievementLabel': '達成率',
    'dashboard.kpi.unitPriceLabel': '標準単価',
    'dashboard.kpi.remainingLabel': '残工数',
    'dashboard.license.card.title': 'CADライセンス管理',
    'dashboard.license.card.subtitle': '年間ライセンス費',
    'dashboard.license.card.costPerHour': 'コスト/時 (計画)',
    'dashboard.gross.plan': '総売上（計画）',
    'dashboard.gross.actual': '総売上（実績）',
    'dashboard.net.plan': '純売上（計画）',
    'dashboard.net.actual': '純売上（実績）',
    'dashboard.net.margin': '利益率',
    'dashboard.costAnalysis.title': 'コスト分析',
    'dashboard.costAnalysis.subtitle': 'ライセンス影響を把握',
    'dashboard.costAnalysis.licensePerHour': 'ライセンス/時',
    'dashboard.costAnalysis.netRate': '実質時給',
    'dashboard.costAnalysis.breakEven': '損益分岐工数',
    'dashboard.charts.cumulative': '累計売上（計画 vs 実績）',
    'dashboard.summary.title': '財務サマリー',
    'dashboard.summary.gross': '総売上（実績）',
    'dashboard.summary.license': 'ライセンス費',
    'dashboard.summary.net': '純売上（実績）',
    'dashboard.summary.margin': '利益率（実績）',
    'dashboard.empty': 'まだダッシュボードデータがありません。トラッキングデータを入力してください。',
    'project.type.mechanical': '機械設計',
    'project.type.software': 'ソフトウェア開発',
    'project.type.translation': '翻訳',
    'project.type.other': 'その他',
    'alerts.projectCreated': 'プロジェクトが正常に作成されました',
    'alerts.projectCreateError': 'プロジェクトの作成に失敗しました',
    'alerts.exportFailed': 'エクスポートに失敗しました',
    'tracker.select': 'Select',
    'tracker.selectAll': 'Select All',
    'tracker.clearSelection': 'Clear Selection',
    'tracker.deleteSelected': 'Delete Selected',
    'tracker.deleteSingle': 'Delete',
    'tracker.selectedLabel': 'Selected',
    'tracker.confirmDeleteMany': 'Delete {count} projects and their records?',
    'tracker.title': 'プロジェクトトラッキング',
    'tracker.expand': '詳細を展開',
    'tracker.collapse': '詳細を折りたたむ',
    'tracker.expandBtn': '展開',
    'tracker.collapseBtn': '折りたたむ',
    'tracker.editOrder': '順序を編集',
    'tracker.done': '完了',
    'tracker.reorderDisabledWithSort': '列でソート中は並び替えできません',
    'tracker.sortDisabled': '並び替えには「No.」列で昇順ソートしてください',
    'tracker.selectMonth': '月を選択...',
    'unsavedChanges': '件の未保存の変更',
    'saveAll': 'すべて保存',
    'saving': '保存中...',
    'noChangesToSave': '保存する変更はありません',
    'changesSavedSuccessfully': 'すべての変更が正常に保存されました！',
    'saveFailed': '変更の保存に失敗しました。もう一度お試しください。',
    'dashboard.kpi.yearTotal': '年度合計',
    'dashboard.license.units': '台',
    'dashboard.license.targetPc': '対象PC',
    'dashboard.notes.allocatePlan': '計画工数で按分',
    'dashboard.notes.unitMinusLicense': '単価 - ライセンス/時',
    'dashboard.notes.breakEven': 'ライセンス費 ÷ 単価',
    'dashboard.perHour': ' / 時',
    'totalView.chartTitle': '年間概要',
    'totalView.axis.monthlyHours': '月間工数',
    'totalView.axis.accumulated': '累計',
    'totalView.tableHeader.type': '業務内容',
    'totalView.tableHeader.total': '合計',
    'totalView.tableHeader.revenue': '売上金額(円)',
    'totalView.tableHeader.title': '年間データテーブル',
    'buttons.exportChart': 'チャートをエクスポート',
    'buttons.exportTable': 'テーブルをエクスポート',
    'nav.periodManagement': '期間管理',
    'periodManagement': '期間管理 / Period Management',
    'managePeriods': '期間を作成し、プロジェクトを割り当てます',
    'createNewPeriod': '新しい期間を作成',
    'existingPeriods': '既存の期間',
    'noPeriodsYet': 'まだ期間が作成されていません',
    'projectCount': 'プロジェクト数',
    'lastUpdated': '最終更新',
    'edit': '編集',
    'delete': '削除',
    'editPeriod': '期間を編集',
    'year': '年',
    'half': '半期',
    'searchProjects': 'プロジェクトを検索',
    'searchPlaceholder': '名前、コード、またはタイプで検索...',
    'projectsSelected': 'プロジェクトが選択されました',
    'selectAll': 'すべて選択',
    'deselectAll': 'すべて解除',
    'noProjectsFound': 'プロジェクトが見つかりません',
    'cancel': 'キャンセル',
    'createPeriod': '期間を作成',
    'updatePeriod': '期間を更新',
    'pleaseSelectAtLeastOneProject': '少なくとも1つのプロジェクトを選択してください',
    'periodCreatedSuccessfully': '期間が正常に作成されました',
    'periodAlreadyExists': 'この期間はすでに存在します',
    'failedToCreatePeriod': '期間の作成に失敗しました',
    'periodUpdatedSuccessfully': '期間が正常に更新されました',
    'failedToUpdatePeriod': '期間の更新に失敗しました',
    'confirmDeletePeriod': '期間 ${period.label} を削除してもよろしいですか？すべてのプロジェクト割り当てが削除されます。',
    'periodDeletedSuccessfully': '期間が正常に削除されました',
    'failedToDeletePeriod': '期間の削除に失敗しました',
    // Long-term Plan View
    'nav.longTermPlan': '長期計画',
    'longTermPlan.title': 'OS事業長期計画',
    'longTermPlan.year': '年度',
    'longTermPlan.salesPlan': '売上計画',
    'longTermPlan.salesActual': '売上実績',
    'longTermPlan.hourlyRatePlan': '平均時給計画',
    'longTermPlan.hourlyRateActual': '平均時給実績',
    'longTermPlan.unit.sales': '万円',
    'longTermPlan.unit.hourlyRate': '千円/時',
    'longTermPlan.axis.year': '年度',
    'longTermPlan.axis.sales': '売上額（万円）',
    'longTermPlan.axis.hourlyRate': '平均時給（千円/時）',
    'longTermPlan.legend.salesPlan': '売上計画（万円）',
    'longTermPlan.legend.salesActual': '売上実績（万円）',
    'longTermPlan.legend.hourlyRatePlan': '平均時給計画',
    'longTermPlan.legend.hourlyRateActual': '平均時給実績',
    'longTermPlan.copyToClipboard': 'チャートをクリップボードにコピー',
    'longTermPlan.exportPNG': 'PNG画像としてエクスポート',
    'longTermPlan.exportSVG': 'SVGとしてエクスポート（ベクター、最高品質）',
    'longTermPlan.exportData': 'チャートデータをCSVとしてエクスポート',
    'buttons.copy': 'コピー',
    // Monthly Plan-Actual View
    'nav.monthlyPlanActual': '年間予実',
    'monthlyPlanActual.title': '年 OS事業受託状況予実',
    'monthlyPlanActual.subtitle': '月次計画と実績の比較',
    'monthlyPlanActual.capacityLine': '能力線',
    'monthlyPlanActual.workingPlan': '稼働計画',
    'monthlyPlanActual.workingActual': '稼働実績',
    'monthlyPlanActual.salesPlan': '売上計画',
    'monthlyPlanActual.salesActual': '売上実績',
    'monthlyPlanActual.unit.sales': '万円',
    'monthlyPlanActual.unit.hours': '時間',
    'monthlyPlanActual.axis.sales': '売上（万円）',
    'monthlyPlanActual.axis.workingHours': '月間稼働時間（時間）',
    'monthlyPlanActual.legend.capacityLine': '能力線',
    'monthlyPlanActual.legend.workingPlan': '稼働計画',
    'monthlyPlanActual.legend.workingActual': '稼働実績',
    'monthlyPlanActual.legend.salesPlan': '売上計画',
    'monthlyPlanActual.legend.salesActual': '売上実績',
    'monthlyPlanActual.copyToClipboard': 'チャートをクリップボードにコピー',
    'monthlyPlanActual.exportPNG': 'PNG画像としてエクスポート',
    'monthlyPlanActual.exportSVG': 'SVGとしてエクスポート（ベクター、最高品質）',
    'monthlyPlanActual.exportData': 'チャートデータをCSVとしてエクスポート',
    'nav.catiaLicense': 'CATIAライセンス管理',
    'toast.saved': '保存しました',
    'toast.saveFailed': '保存に失敗しました',
    'toast.loadFailed': 'データの読み込みに失敗しました',
    'toast.deleted': '削除しました',
    'toast.deleteFailed': '削除に失敗しました',
    'toast.exportDone': 'エクスポートが完了しました',
    'toast.exportFailed': 'エクスポートに失敗しました',
    'toast.copied': 'クリップボードにコピーしました',
    'toast.copyFailed': 'コピーに失敗しました',
    'toast.codeFailed': 'プロジェクトコードの生成に失敗しました',
    'toast.nothingToSave': '保存する変更はありません',
    'common.confirm': '確認',
    'common.cancel': 'キャンセル',
    'common.close': '閉じる',
    'common.leave': '移動する',
    'common.stay': '留まる',
    'common.viewOnly': '閲覧のみ',
    'common.loading': '読み込み中…',
    'tracker.adminOnly': '管理者のみ編集できます',
    'tracker.unsavedTitle': '未保存の変更があります',
    'tracker.unsavedLeaveConfirm': '未保存の変更があります。保存せずに移動しますか？',
    'tracker.savedCount': '{count}件の変更を保存しました',
    'tracker.confirmDeleteProject': 'このプロジェクトを削除しますか？この操作は取り消せません。',
    'language.select': '言語を選択',
    'dashboard.noDataForYear': '{year}年のデータはありません',
    'dashboard.licenseSyncing': 'ライセンスデータを同期中…',
    'catia.syncing': '同期中…',
    'catia.synced': 'サーバーと同期済み',
    'catia.syncError': '同期に失敗しました。ローカルの値を表示しています',
    'catia.resetConfirm': 'すべてのCATIAライセンス値を初期値に戻しますか？',
    'catia.title': 'CATIAライセンス管理',
    'catia.costTab': 'ライセンス費用（万円/月）',
    'catia.revenueTab': 'ライセンス収入（万円/年）',
    'catia.license': 'ライセンス',
    'catia.resetDefaults': '初期値に戻す',
    'catia.subtitle': 'ライセンスROIとコストのインタラクティブ管理',
    'catia.totalCostForYear': '{year}年のライセンス費用合計',
    'catia.infoEditable': 'この表はインタラクティブです。数値セルをクリックすると、Excelと同じように編集できます。',
    'catia.infoAutoRecalc': '変更はサーバーに保存され、ダッシュボードのチャートで使用する{year}年の合計費用が即座に再計算されます。',
    'catia.month': '月',
    'catia.purchase': '買取',
    'catia.lease': 'リース',
    'catia.tipLabel': 'ヒント',
    'catia.tipTooltip': '数値セルにカーソルを合わせると、丸めていない正確な値がツールチップで表示されます。',
    'catia.tipEditable': '値は月単位でここから更新できます。コードの変更は不要です。',
    'catia.manYenUnit': '万',
    'modals.project.planPrice': '計画単価（円/時）',
    'modals.project.actualPrice': '実績単価（円/時）',
    'modals.project.priceRequired': '計画単価を入力してください',
    'modals.project.created': 'プロジェクトを作成しました',
    'modals.project.createFailed': 'プロジェクトの作成に失敗しました',
    'editProject.saved': 'プロジェクトを更新しました',
    'editProject.saveFailed': 'プロジェクトの更新に失敗しました',
    'editProject.softwarePlaceholder': 'AutoCAD、Revit など',
    'editProject.softwareHint': '複数のソフトウェア名はカンマまたは改行で区切って入力してください。',
    'editProject.notesPlaceholder': '備考...',
    'alerts.duplicatePeriod': 'この期間は既に存在します',
    'alerts.periodCreated': '期間を作成しました',
    'alerts.periodCreateFailed': '期間の作成に失敗しました',
    'alerts.projectsLoadFailed': 'プロジェクトの読み込みに失敗しました',
    'periodManagement.selectProjects': '少なくとも1つのプロジェクトを選択してください',
    'periodManagement.updated': '期間を更新しました',
    'periodManagement.updateFailed': '期間の更新に失敗しました',
    'periodManagement.deleted': '期間を削除しました',
    'periodManagement.deleteFailed': '期間の削除に失敗しました',
    'periodManagement.confirmDelete': 'この期間と紐づくデータを削除しますか？',
    'periodManagement.copied': 'プロジェクトをコピーしました',
    'periodManagement.copyFailed': 'プロジェクトのコピーに失敗しました',
    'common.edit': '編集',
    'common.delete': '削除',
    'common.moveUp': '上へ移動',
    'common.moveDown': '下へ移動',
    'common.save': '変更を保存',
    'common.saving': '保存中...',
    'tracker.exclusion': '除外',
    'totalView.tableHeader.price': '単価',
    'details.planPrice': '計画単価',
    'details.actualPrice': '実績単価',
    'modal.editProject': 'プロジェクトを編集',
    'dashboard.kpi.actualHoursDesc': '年間実績合計',
    'dashboard.kpi.varianceLabel': '差異',
    'dashboard.net.plan.subtitle': '計画売上 - ライセンス',
    'dashboard.net.actual.subtitle': '実績売上 - ライセンス',
    'export.sections': 'セクションをエクスポート',
    'export.copyAsImage': 'クリップボードにコピー',
  },
  en: {
    'app.title': 'OS Manager',
    'app.subtitle': 'Esuhai Group',
    'nav.dashboard': 'Dashboard',
    'nav.tracking': 'Project Tracking',
    'nav.totalView': 'Charts View',
    'nav.yearlyData': 'Annual Data',
    'nav.signOut': 'Sign Out',
    'header.dashboardTitle': 'Dashboard',
    'header.performance': 'Performance Overview',
    'header.exchangeRate': 'Exchange Rate (JPY → VND)',
    'search.placeholder': 'Search projects...',
    'buttons.export': 'Export',
    'export.options': 'Export Options',
    'chartExport.notFound': 'Chart not found, nothing was exported',
    'chart.colors': 'Colors',
    'chart.customizeColors': 'Customize chart colors',
    'chart.highlightCurrentMonth': 'Highlight current month',
    'chart.thisMonth': 'This month',
    'chart.dataCsv': 'Data',
    'chart.field.color': 'Color',
    'chart.field.alpha': 'Alpha',
    'chart.field.text': 'Text',
    'chart.field.size': 'Size',
    'chart.field.width': 'Width',
    'chart.field.bold': 'Bold',
    'chart.field.outline': 'Outline',
    'totalView.timeGap': 'Time gap',
    'totalView.percentGap': '% gap',
    'chartExport.noChart': 'No chart found to export',
    'chartExport.notFoundCopy': 'Chart not found, nothing was copied',
    'chartExport.noData': 'There is no data to export',
    'chartExport.pngFailed': 'Export failed: could not create the PNG image',
    'chartExport.done': 'Export complete',
    'chartExport.copied': 'Copied to clipboard',
    'chartExport.failed': 'Export failed',
    'chartExport.copyFailed': 'Copy failed',
    'export.copyImage': 'Copy Image',
    'export.copied': 'Copied!',
    'export.savePNG': 'Save as PNG',
    'export.saveSVG': 'Save as SVG',
    'export.downloadData': 'Download Data (Excel/CSV)',
    'buttons.project': 'Project',
    'buttons.language.jp': 'Japanese',
    'buttons.language.en': 'English',
    'buttons.language.vn': 'Vietnamese',
    'app.adminUser': 'Admin User',
    'modals.project.title': 'Add New Project',
    'modals.project.code': 'Project Code',
    'modals.project.name': 'Company Name',
    'modals.project.type': 'Business Content',
    'modals.project.typePlaceholder': 'Mechanical Design',
    'modals.project.software': 'Software',
    'modals.project.softwarePlaceholder': 'AutoCAD',
    'modals.actions.cancel': 'Cancel',
    'modals.project.submit': 'Create Project',
    'modals.period.title': 'New Period',
    'modals.period.year': 'Year',
    'modals.period.half': 'Half',
    'modals.period.option.h1': 'H1 (Jan-Jun)',
    'modals.period.option.h2': 'H2 (Jul-Dec)',
    'modals.period.submit': 'Add Period',
    'modals.period.subtitle': 'Create a new period and select projects to include',
    'modals.period.selectProjects': 'Select existing projects',
    'modals.period.selectProjectsHint': 'Select existing projects to include in this period',
    'modals.period.noProjects': 'No projects yet',
    'modals.period.noProjectsHint': 'Create a project first.',
    'auth.subtitle': 'Local Data Environment',
    'auth.info': 'This is a local demonstration version. No server connection required.',
    'auth.button': 'Enter Application',
    'auth.loading': 'Accessing System...',
    'tracker.no': 'No.',
    'tracker.reorderFailed': 'Could not save the new order. Please refresh.',
    'tracker.moveFailed': 'Could not move the project. Please refresh.',
    'tracker.unsavedKept': 'Your unsaved changes were kept. Use Save All to store them.',
    'tracker.code': 'Code',
    'tracker.exclusionMark': 'Exclusion Mark',
    'tracker.projectName': 'Company Name',
    'tracker.notes': 'Notes',
    'tracker.software': 'Software',
    'tracker.businessContent': 'Business Content',
    'tracker.type': 'Type',
    'tracker.unitPrice': 'Unit Price (JPY)',
    'tracker.actions': 'Actions',
    'tracker.moveUp': 'Move Up',
    'tracker.moveDown': 'Move Down',
    'tracker.monthSuffix': ' Month',
    'tracker.monthSubLabel': 'Plan / Actual',
    'tracker.planShort': 'Plan',
    'tracker.actualShort': 'Actual',
    'tracker.totalHrs': 'Total Hours',
    'tracker.revenue': 'Revenue',
    'tracker.totalHrsPlan': 'Total Hours (Plan)',
    'tracker.totalHrsActual': 'Total Hours (Actual)',
    'tracker.revenuePlan': 'Revenue (Plan)',
    'tracker.revenueActual': 'Revenue (Actual)',
    'tracker.noResults': 'No projects found matching your search.',
    'dashboard.kpi.totalRevenue': 'Total Revenue (Actual)',
    'export.kpiSummary': 'Performance Highlights (KPI – Licence)',
    'export.costAnalysis': 'Cost Analysis',
    'export.financialSummary': 'Financial Summary',
    'dashboard.kpi.varianceDesc': 'Actual - Plan',
    'periodManagement.monthRange.h1': 'Jan-Jun',
    'periodManagement.monthRange.h2': 'Jul-Dec',
    'dashboard.colors.title': 'Customize Dashboard Colors',
    'dashboard.colors.headingSize': 'Heading Size',
    'dashboard.colors.reset': 'Reset Defaults',
    'dashboard.colors.from': 'From',
    'dashboard.colors.to': 'To',
    'dashboard.colors.gradientSuffix': '(Gradient)',
    'dashboard.colors.cardBorders': 'Card Borders (Solid)',
    'dashboard.colors.chartTitle': 'Customize chart colors',
    'dashboard.colors.button': 'Colors',
    'dashboard.summary.netOverGross': 'Net / Gross',
    'dashboard.kpi.revenueAchievement': 'Revenue Achievement',
    'dashboard.kpi.totalHours': 'Total Hours',
    'dashboard.kpi.plannedRevenue': 'Planned Revenue',
    'dashboard.kpi.targetLabel': 'Target',
    'dashboard.kpi.planLabel': 'Plan',
    'dashboard.chart.monthly': 'Monthly Revenue: Plan vs Actual',
    'dashboard.chart.accumulated': 'Accumulated Revenue Trend',
    'dashboard.chart.accActual': 'Accumulated Actual',
    'dashboard.chart.accPlan': 'Accumulated Plan',
    'dashboard.header.desc': 'Review progress and revenue by year',
    'dashboard.fx.label': 'Exchange Rate',
    'dashboard.fx.hourly': 'Hourly Rate (JPY)',
    'dashboard.license.count': 'License Seats',
    'dashboard.license.perSeat': 'Fee per Seat (JPY)',
    'dashboard.license.total': 'Annual License Cost',
    'dashboard.kpi.planHoursLabel': 'Planned Hours',
    'dashboard.kpi.actualHoursLabel': 'Actual Hours',
    'dashboard.kpi.achievementLabel': 'Achievement',
    'dashboard.kpi.unitPriceLabel': 'Unit Rate',
    'dashboard.kpi.remainingLabel': 'Remaining Hours',
    'dashboard.license.card.title': 'CAD License Management',
    'dashboard.license.card.subtitle': 'Annual License Fee',
    'dashboard.license.card.costPerHour': 'Cost per Hour (plan)',
    'dashboard.gross.plan': 'Gross Revenue (Plan)',
    'dashboard.gross.actual': 'Gross Revenue (Actual)',
    'dashboard.net.plan': 'Net Revenue (Plan)',
    'dashboard.net.actual': 'Net Revenue (Actual)',
    'dashboard.net.margin': 'Profit Margin',
    'dashboard.costAnalysis.title': 'Cost Analysis',
    'dashboard.costAnalysis.subtitle': 'Understand license impact',
    'dashboard.costAnalysis.licensePerHour': 'License / Hour',
    'dashboard.costAnalysis.netRate': 'Net Hourly Rate',
    'dashboard.costAnalysis.breakEven': 'Break-even Hours',
    'dashboard.charts.cumulative': 'Cumulative Revenue (Plan vs Actual)',
    'dashboard.summary.title': 'Financial Summary',
    'dashboard.summary.gross': 'Gross (Actual)',
    'dashboard.summary.license': 'License Cost',
    'dashboard.summary.net': 'Net (Actual)',
    'dashboard.summary.margin': 'Margin (Actual)',
    'dashboard.empty': 'No dashboard data available yet. Add tracking records to view analytics.',
    'project.type.mechanical': 'Mechanical Design',
    'project.type.software': 'Software Development',
    'project.type.translation': 'Translation',
    'project.type.other': 'Other',
    'alerts.projectCreated': 'Project created successfully!',
    'alerts.projectCreateError': 'Error creating project',
    'alerts.exportFailed': 'Export failed',
    'tracker.select': 'Select',
    'tracker.selectAll': 'Select All',
    'tracker.clearSelection': 'Clear Selection',
    'tracker.deleteSelected': 'Delete Selected',
    'tracker.deleteSingle': 'Delete',
    'tracker.selectedLabel': 'Selected',
    'tracker.confirmDeleteMany': 'Delete {count} projects and their records?',
    'tracker.title': 'Project Tracking',
    'tracker.expand': 'Expand details',
    'tracker.collapse': 'Collapse details',
    'tracker.expandBtn': 'Expand',
    'tracker.collapseBtn': 'Collapse',
    'tracker.editOrder': 'Edit Order',
    'tracker.done': 'Done',
    'tracker.reorderDisabledWithSort': 'Reordering disabled while sorted',
    'tracker.sortDisabled': 'Sort by No. to reorder',
    'tracker.selectMonth': 'Select Month...',
    'unsavedChanges': 'unsaved changes',
    'saveAll': 'Save All',
    'saving': 'Saving...',
    'noChangesToSave': 'No changes to save',
    'changesSavedSuccessfully': 'All changes saved successfully!',
    'saveFailed': 'Failed to save changes. Please try again.',
    'dashboard.kpi.yearTotal': 'Year Total',
    'dashboard.license.units': 'units',
    'dashboard.license.targetPc': 'Target PCs',
    'dashboard.notes.allocatePlan': 'Allocated over planned hours',
    'dashboard.notes.unitMinusLicense': 'Unit rate - license/hour',
    'dashboard.notes.breakEven': 'License cost ÷ unit rate',
    'dashboard.perHour': ' / hour',
    'totalView.chartTitle': 'Yearly Overview',
    'totalView.axis.monthlyHours': 'Monthly Hours',
    'totalView.axis.accumulated': 'Accumulated',
    'totalView.tableHeader.type': 'Business Content',
    'totalView.tableHeader.total': 'Total',
    'totalView.tableHeader.revenue': 'Revenue (JPY)',
    'totalView.tableHeader.title': 'Yearly Data Table',
    'buttons.exportChart': 'Export Chart',
    'buttons.exportTable': 'Export Table',
    'nav.periodManagement': 'Period Management',
    'periodManagement': 'Period Management',
    'managePeriods': 'Create and manage periods with project assignments',
    'createNewPeriod': 'Create New Period',
    'existingPeriods': 'Existing Periods',
    'noPeriodsYet': 'No periods created yet',
    'projectCount': 'Projects',
    'lastUpdated': 'Last updated',
    'edit': 'Edit',
    'delete': 'Delete',
    'editPeriod': 'Edit Period',
    'year': 'Year',
    'half': 'Half',
    'searchProjects': 'Search Projects',
    'searchPlaceholder': 'Search by name, code, or type...',
    'projectsSelected': 'projects selected',
    'selectAll': 'Select All',
    'deselectAll': 'Deselect All',
    'noProjectsFound': 'No projects found',
    'cancel': 'Cancel',
    'createPeriod': 'Create Period',
    'updatePeriod': 'Update Period',
    'pleaseSelectAtLeastOneProject': 'Please select at least one project',
    'periodCreatedSuccessfully': 'Period created successfully',
    'periodAlreadyExists': 'This period already exists',
    'failedToCreatePeriod': 'Failed to create period',
    'periodUpdatedSuccessfully': 'Period updated successfully',
    'failedToUpdatePeriod': 'Failed to update period',
    'confirmDeletePeriod': 'Are you sure you want to delete period ${period.label}? This will remove all project assignments.',
    'periodDeletedSuccessfully': 'Period deleted successfully',
    'failedToDeletePeriod': 'Failed to delete period',
    // Long-term Plan View
    'nav.longTermPlan': 'Long-term Plan',
    'longTermPlan.title': 'OS Business Long-term Plan',
    'longTermPlan.year': 'Year',
    'longTermPlan.salesPlan': 'Sales Plan',
    'longTermPlan.salesActual': 'Sales Actual',
    'longTermPlan.hourlyRatePlan': 'Avg. Hourly Rate Plan',
    'longTermPlan.hourlyRateActual': 'Avg. Hourly Rate Actual',
    'longTermPlan.unit.sales': '10k JPY',
    'longTermPlan.unit.hourlyRate': 'k JPY/hr',
    'longTermPlan.axis.year': 'Year',
    'longTermPlan.axis.sales': 'Sales Amount (10k JPY)',
    'longTermPlan.axis.hourlyRate': 'Avg. Hourly Rate (k JPY/hr)',
    'longTermPlan.legend.salesPlan': 'Sales Plan (10k JPY)',
    'longTermPlan.legend.salesActual': 'Sales Actual (10k JPY)',
    'longTermPlan.legend.hourlyRatePlan': 'Avg. Hourly Rate Plan',
    'longTermPlan.legend.hourlyRateActual': 'Avg. Hourly Rate Actual',
    'longTermPlan.copyToClipboard': 'Copy chart to clipboard',
    'longTermPlan.exportPNG': 'Export as PNG image',
    'longTermPlan.exportSVG': 'Export as SVG (vector, best quality)',
    'longTermPlan.exportData': 'Export chart data as CSV',
    'buttons.copy': 'Copy',
    // Monthly Plan-Actual View
    'nav.monthlyPlanActual': 'Monthly Plan-Actual',
    'monthlyPlanActual.title': ' OS Business Monthly Plan-Actual',
    'monthlyPlanActual.subtitle': 'Monthly plan vs actual comparison',
    'monthlyPlanActual.capacityLine': 'Capacity Line',
    'monthlyPlanActual.workingPlan': 'Working Hours Plan',
    'monthlyPlanActual.workingActual': 'Working Hours Actual',
    'monthlyPlanActual.salesPlan': 'Sales Plan',
    'monthlyPlanActual.salesActual': 'Sales Actual',
    'monthlyPlanActual.unit.sales': '10k JPY',
    'monthlyPlanActual.unit.hours': 'hrs',
    'monthlyPlanActual.axis.sales': 'Sales (10k JPY)',
    'monthlyPlanActual.axis.workingHours': 'Monthly Working Hours (hrs)',
    'monthlyPlanActual.legend.capacityLine': 'Capacity Line',
    'monthlyPlanActual.legend.workingPlan': 'Working Hours Plan',
    'monthlyPlanActual.legend.workingActual': 'Working Hours Actual',
    'monthlyPlanActual.legend.salesPlan': 'Sales Plan',
    'monthlyPlanActual.legend.salesActual': 'Sales Actual',
    'monthlyPlanActual.copyToClipboard': 'Copy chart to clipboard',
    'monthlyPlanActual.exportPNG': 'Export as PNG image',
    'monthlyPlanActual.exportSVG': 'Export as SVG (vector, best quality)',
    'monthlyPlanActual.exportData': 'Export chart data as CSV',
    'nav.catiaLicense': 'CATIA License',
    'toast.saved': 'Saved',
    'toast.saveFailed': 'Save failed',
    'toast.loadFailed': 'Failed to load data',
    'toast.deleted': 'Deleted',
    'toast.deleteFailed': 'Delete failed',
    'toast.exportDone': 'Export complete',
    'toast.exportFailed': 'Export failed',
    'toast.copied': 'Copied to clipboard',
    'toast.copyFailed': 'Copy failed',
    'toast.codeFailed': 'Could not generate a project code',
    'toast.nothingToSave': 'No changes to save',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.leave': 'Leave',
    'common.stay': 'Stay',
    'common.viewOnly': 'View only',
    'common.loading': 'Loading…',
    'tracker.adminOnly': 'Only admins can edit',
    'tracker.unsavedTitle': 'Unsaved changes',
    'tracker.unsavedLeaveConfirm': 'You have unsaved changes. Leave without saving?',
    'tracker.savedCount': 'Saved {count} change(s)',
    'tracker.confirmDeleteProject': 'Delete this project? This cannot be undone.',
    'language.select': 'Select language',
    'dashboard.noDataForYear': 'No data for {year}',
    'dashboard.licenseSyncing': 'Syncing license data…',
    'catia.syncing': 'Syncing…',
    'catia.synced': 'Synced with server',
    'catia.syncError': 'Sync failed — showing local values',
    'catia.resetConfirm': 'Reset all CATIA license values to defaults?',
    'catia.title': 'CATIA License Management',
    'catia.costTab': 'License cost (10k JPY / month)',
    'catia.revenueTab': 'License revenue (10k JPY / year)',
    'catia.license': 'License',
    'catia.resetDefaults': 'Reset to defaults',
    'catia.subtitle': 'Interactive License ROI and Cost Tracking',
    'catia.totalCostForYear': 'Total {year} license cost',
    'catia.infoEditable': 'This table is interactive — click any number cell to edit it, just like in Excel.',
    'catia.infoAutoRecalc': 'Every change is saved to the server and immediately recalculates the {year} total cost used by the Dashboard charts.',
    'catia.month': 'Month',
    'catia.purchase': 'Purchase',
    'catia.lease': 'Lease',
    'catia.tipLabel': 'Tip',
    'catia.tipTooltip': 'Hover a number cell to see the full, unrounded value in a tooltip.',
    'catia.tipEditable': 'Values can be updated here month by month — no code change needed.',
    'catia.manYenUnit': '万',
    'modals.project.planPrice': 'Plan price (JPY/h)',
    'modals.project.actualPrice': 'Actual price (JPY/h)',
    'modals.project.priceRequired': 'Plan price is required',
    'modals.project.created': 'Project created',
    'modals.project.createFailed': 'Failed to create project',
    'editProject.saved': 'Project updated',
    'editProject.saveFailed': 'Failed to update project',
    'editProject.softwarePlaceholder': 'AutoCAD, Revit, etc.',
    'editProject.softwareHint': 'Enter multiple software names, separated by commas or new lines.',
    'editProject.notesPlaceholder': 'Notes...',
    'alerts.duplicatePeriod': 'This period already exists',
    'alerts.periodCreated': 'Period created',
    'alerts.periodCreateFailed': 'Failed to create period',
    'alerts.projectsLoadFailed': 'Failed to load projects',
    'periodManagement.selectProjects': 'Select at least one project',
    'periodManagement.updated': 'Period updated',
    'periodManagement.updateFailed': 'Failed to update period',
    'periodManagement.deleted': 'Period deleted',
    'periodManagement.deleteFailed': 'Failed to delete period',
    'periodManagement.confirmDelete': 'Delete this period and its linked data?',
    'periodManagement.copied': 'Projects copied',
    'periodManagement.copyFailed': 'Failed to copy projects',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.moveUp': 'Move Up',
    'common.moveDown': 'Move Down',
    'common.save': 'Save Changes',
    'common.saving': 'Saving...',
    'tracker.exclusion': 'Exclusion',
    'totalView.tableHeader.price': 'Price',
    'details.planPrice': 'Plan Price',
    'details.actualPrice': 'Actual Price',
    'modal.editProject': 'Edit Project',
    'dashboard.kpi.actualHoursDesc': 'Year Actual Total',
    'dashboard.kpi.varianceLabel': 'Variance',
    'dashboard.net.plan.subtitle': 'Plan revenue - license cost',
    'dashboard.net.actual.subtitle': 'Actual revenue - license cost',
    'export.sections': 'Export Section',
    'export.copyAsImage': 'Copy to Clipboard',
  },
  vn: {
    'app.title': 'Hệ thống quản lý OS',
    'app.subtitle': 'Tập đoàn Esuhai',
    'nav.dashboard': 'Bảng điều khiển',
    'nav.tracking': 'Theo dõi dự án',
    'nav.totalView': 'Biểu đồ',
    'nav.yearlyData': 'Dữ liệu năm',
    'nav.signOut': 'Đăng xuất',
    'header.dashboardTitle': 'Bảng điều khiển',
    'header.performance': 'Tổng quan hiệu suất',
    'header.exchangeRate': 'Tỷ giá (JPY → VND)',
    'search.placeholder': 'Tìm kiếm dự án...',
    'buttons.export': 'Xuất',
    'export.options': 'Tùy chọn xuất',
    'chartExport.notFound': 'Không tìm thấy biểu đồ, không có gì được xuất',
    'chart.colors': 'Màu sắc',
    'chart.customizeColors': 'Tùy chỉnh màu biểu đồ',
    'chart.highlightCurrentMonth': 'Làm nổi bật tháng hiện tại',
    'chart.thisMonth': 'Tháng này',
    'chart.dataCsv': 'Dữ liệu',
    'chart.field.color': 'Màu',
    'chart.field.alpha': 'Độ mờ',
    'chart.field.text': 'Chữ',
    'chart.field.size': 'Cỡ',
    'chart.field.width': 'Độ dày',
    'chart.field.bold': 'In đậm',
    'chart.field.outline': 'Viền',
    'totalView.timeGap': 'Chênh lệch giờ',
    'totalView.percentGap': 'Chênh lệch %',
    'chartExport.noChart': 'Không tìm thấy biểu đồ để xuất',
    'chartExport.notFoundCopy': 'Không tìm thấy biểu đồ, không có gì được sao chép',
    'chartExport.noData': 'Không có dữ liệu để xuất',
    'chartExport.pngFailed': 'Xuất thất bại: không thể tạo ảnh PNG',
    'chartExport.done': 'Xuất hoàn tất',
    'chartExport.copied': 'Đã sao chép vào clipboard',
    'chartExport.failed': 'Xuất thất bại',
    'chartExport.copyFailed': 'Sao chép thất bại',
    'export.copyImage': 'Sao chép ảnh',
    'export.copied': 'Đã sao chép!',
    'export.savePNG': 'Lưu dạng PNG',
    'export.saveSVG': 'Lưu dạng SVG',
    'export.downloadData': 'Tải dữ liệu (Excel/CSV)',
    'buttons.project': 'Dự án',
    'buttons.language.jp': 'Tiếng Nhật',
    'buttons.language.en': 'Tiếng Anh',
    'buttons.language.vn': 'Tiếng Việt',
    'app.adminUser': 'Quản trị viên',
    'modals.project.title': 'Thêm dự án mới',
    'modals.project.code': 'Mã dự án',
    'modals.project.name': 'Tên công ty',
    'modals.project.type': 'Nội dung kinh doanh',
    'modals.project.typePlaceholder': 'Thiết kế cơ khí',
    'modals.project.software': 'Phần mềm',
    'modals.project.softwarePlaceholder': 'AutoCAD',
    'modals.actions.cancel': 'Hủy',
    'modals.project.submit': 'Tạo dự án',
    'modals.period.title': 'Kỳ mới',
    'modals.period.year': 'Năm',
    'modals.period.half': 'Nửa kỳ',
    'modals.period.option.h1': 'H1 (Thg 1-6)',
    'modals.period.option.h2': 'H2 (Thg 7-12)',
    'modals.period.submit': 'Thêm kỳ',
    'modals.period.subtitle': 'Tạo kỳ mới và chọn các dự án cần đưa vào',
    'modals.period.selectProjects': 'Chọn dự án hiện có',
    'modals.period.selectProjectsHint': 'Chọn các dự án hiện có để đưa vào kỳ này',
    'modals.period.noProjects': 'Chưa có dự án nào',
    'modals.period.noProjectsHint': 'Hãy tạo một dự án trước.',
    'auth.subtitle': 'Môi trường dữ liệu cục bộ',
    'auth.info': 'Đây là bản demo cục bộ, không cần kết nối máy chủ.',
    'auth.button': 'Truy cập ứng dụng',
    'auth.loading': 'Đang truy cập hệ thống...',
    'tracker.no': 'No.',
    'tracker.reorderFailed': 'Không thể lưu thứ tự mới. Vui lòng tải lại trang.',
    'tracker.moveFailed': 'Không thể di chuyển dự án. Vui lòng tải lại trang.',
    'tracker.unsavedKept': 'Các thay đổi chưa lưu vẫn được giữ. Dùng "Lưu tất cả" để lưu lại.',
    'tracker.code': 'Mã',
    'tracker.exclusionMark': 'Ký hiệu loại trừ',
    'tracker.projectName': 'Tên công ty',
    'tracker.notes': 'Ghi chú',
    'tracker.software': 'Phần mềm',
    'tracker.businessContent': 'Nội dung kinh doanh',
    'tracker.type': 'Loại',
    'tracker.unitPrice': 'Đơn giá (JPY)',
    'tracker.actions': 'Hành động',
    'tracker.moveUp': 'Di chuyển lên',
    'tracker.moveDown': 'Di chuyển xuống',
    'tracker.monthSuffix': ' Tháng',
    'tracker.monthSubLabel': 'Kế hoạch / Thực tế',
    'tracker.planShort': 'Kế hoạch',
    'tracker.actualShort': 'Thực tế',
    'tracker.totalHrs': 'Tổng giờ',
    'tracker.revenue': 'Doanh thu',
    'tracker.totalHrsPlan': 'Tổng giờ (KH)',
    'tracker.totalHrsActual': 'Tổng giờ (TT)',
    'tracker.revenuePlan': 'Doanh thu (KH)',
    'tracker.revenueActual': 'Doanh thu (TT)',
    'tracker.noResults': 'Không tìm thấy dự án phù hợp.',
    'dashboard.kpi.totalRevenue': 'Tổng doanh thu (Thực tế)',
    'export.kpiSummary': 'Chỉ số nổi bật (KPI – Bản quyền)',
    'export.costAnalysis': 'Phân tích chi phí',
    'export.financialSummary': 'Tóm tắt tài chính',
    'dashboard.kpi.varianceDesc': 'Thực tế - Kế hoạch',
    'periodManagement.monthRange.h1': 'Thg 1-6',
    'periodManagement.monthRange.h2': 'Thg 7-12',
    'dashboard.colors.title': 'Tùy chỉnh màu bảng điều khiển',
    'dashboard.colors.headingSize': 'Cỡ tiêu đề',
    'dashboard.colors.reset': 'Khôi phục mặc định',
    'dashboard.colors.from': 'Từ',
    'dashboard.colors.to': 'Đến',
    'dashboard.colors.gradientSuffix': '(Chuyển sắc)',
    'dashboard.colors.cardBorders': 'Viền thẻ (màu đặc)',
    'dashboard.colors.chartTitle': 'Tùy chỉnh màu biểu đồ',
    'dashboard.colors.button': 'Màu sắc',
    'dashboard.summary.netOverGross': 'Lợi nhuận ròng / Tổng doanh thu',
    'dashboard.kpi.revenueAchievement': 'Tỷ lệ hoàn thành doanh thu',
    'dashboard.kpi.totalHours': 'Tổng giờ',
    'dashboard.kpi.plannedRevenue': 'Doanh thu kế hoạch',
    'dashboard.kpi.targetLabel': 'Mục tiêu',
    'dashboard.kpi.planLabel': 'Kế hoạch',
    'dashboard.chart.monthly': 'Doanh thu hàng tháng: KH vs TT',
    'dashboard.chart.accumulated': 'Xu hướng doanh thu lũy kế',
    'dashboard.chart.accActual': 'Lũy kế thực tế',
    'dashboard.chart.accPlan': 'Lũy kế kế hoạch',
    'dashboard.header.desc': 'Xem tiến độ và doanh thu theo năm',
    'dashboard.fx.label': 'Tỷ giá',
    'dashboard.fx.hourly': 'Đơn giá giờ (JPY)',
    'dashboard.license.count': 'Số máy bản quyền',
    'dashboard.license.perSeat': 'Phí mỗi máy (JPY)',
    'dashboard.license.total': 'Chi phí bản quyền năm',
    'dashboard.kpi.planHoursLabel': 'Giờ kế hoạch',
    'dashboard.kpi.actualHoursLabel': 'Giờ thực tế',
    'dashboard.kpi.achievementLabel': 'Hoàn thành',
    'dashboard.kpi.unitPriceLabel': 'Đơn giá giờ',
    'dashboard.kpi.remainingLabel': 'Giờ còn lại',
    'dashboard.license.card.title': 'Quản lý bản quyền CAD',
    'dashboard.license.card.subtitle': 'Phí bản quyền hằng năm',
    'dashboard.license.card.costPerHour': 'Chi phí/giờ (kế hoạch)',
    'dashboard.gross.plan': 'Doanh thu gộp (Kế hoạch)',
    'dashboard.gross.actual': 'Doanh thu gộp (Thực tế)',
    'dashboard.net.plan': 'Doanh thu ròng (Kế hoạch)',
    'dashboard.net.actual': 'Doanh thu ròng (Thực tế)',
    'dashboard.net.margin': 'Biên lợi nhuận',
    'dashboard.costAnalysis.title': 'Phân tích chi phí',
    'dashboard.costAnalysis.subtitle': 'Hiểu tác động của bản quyền',
    'dashboard.costAnalysis.licensePerHour': 'Bản quyền / giờ',
    'dashboard.costAnalysis.netRate': 'Đơn giá ròng',
    'dashboard.costAnalysis.breakEven': 'Giờ hòa vốn',
    'dashboard.charts.cumulative': 'Doanh thu lũy kế (KH vs TT)',
    'dashboard.summary.title': 'Tóm tắt tài chính',
    'dashboard.summary.gross': 'Doanh thu gộp (Thực tế)',
    'dashboard.summary.license': 'Chi phí bản quyền',
    'dashboard.summary.net': 'Doanh thu ròng (Thực tế)',
    'dashboard.summary.margin': 'Biên lợi nhuận (Thực tế)',
    'dashboard.empty': 'Chưa có dữ liệu bảng điều khiển. Thêm bản ghi theo dõi để xem phân tích.',
    'project.type.mechanical': 'Thiết kế cơ khí',
    'project.type.software': 'Phát triển phần mềm',
    'project.type.translation': 'Biên dịch',
    'project.type.other': 'Khác',
    'alerts.projectCreated': 'Dự án đã được tạo thành công!',
    'alerts.projectCreateError': 'Lỗi khi tạo dự án',
    'alerts.exportFailed': 'Xuất dữ liệu thất bại',
    'tracker.select': 'Chọn',
    'tracker.selectAll': 'Chọn tất cả',
    'tracker.clearSelection': 'Bỏ chọn',
    'tracker.deleteSelected': 'Xóa đã chọn',
    'tracker.deleteSingle': 'Xóa',
    'tracker.selectedLabel': 'Đã chọn',
    'tracker.confirmDeleteMany': 'Xóa {count} dự án và các bản ghi liên quan?',
    'tracker.title': 'Theo dõi dự án',
    'tracker.expand': 'Mở rộng chi tiết',
    'tracker.collapse': 'Thu gọn chi tiết',
    'tracker.expandBtn': 'Mở rộng',
    'tracker.collapseBtn': 'Thu gọn',
    'tracker.editOrder': 'Chỉnh thứ tự',
    'tracker.done': 'Hoàn thành',
    'tracker.reorderDisabledWithSort': 'Không thể sắp xếp khi đang lọc cột',
    'tracker.sortDisabled': 'Sắp xếp theo cột "No." để chỉnh thứ tự',
    'tracker.selectMonth': 'Chọn Tháng...',
    'unsavedChanges': 'thay đổi chưa lưu',
    'saveAll': 'Lưu tất cả',
    'saving': 'Đang lưu...',
    'noChangesToSave': 'Không có thay đổi để lưu',
    'changesSavedSuccessfully': 'Tất cả thay đổi đã được lưu thành công!',
    'saveFailed': 'Lưu thay đổi thất bại. Vui lòng thử lại.',
    'dashboard.kpi.yearTotal': 'Tổng năm',
    'dashboard.license.units': 'máy',
    'dashboard.license.targetPc': 'PC mục tiêu',
    'dashboard.notes.allocatePlan': 'Phân bổ trên giờ kế hoạch',
    'dashboard.notes.unitMinusLicense': 'Đơn giá - bản quyền/giờ',
    'dashboard.notes.breakEven': 'Chi phí bản quyền ÷ đơn giá',
    'dashboard.perHour': ' / giờ',
    'totalView.chartTitle': 'Tổng quan năm',
    'totalView.axis.monthlyHours': 'Giờ hàng tháng',
    'totalView.axis.accumulated': 'Lũy kế',
    'totalView.tableHeader.type': 'Nội dung kinh doanh',
    'totalView.tableHeader.total': 'Tổng',
    'totalView.tableHeader.revenue': 'Doanh thu (JPY)',
    'totalView.tableHeader.title': 'Bảng dữ liệu hàng năm',
    'buttons.exportChart': 'Xuất biểu đồ',
    'buttons.exportTable': 'Xuất bảng',
    'nav.periodManagement': 'Quản lý kỳ',
    'periodManagement': 'Quản lý kỳ / Period Management',
    'managePeriods': 'Tạo và quản lý các kỳ với phân công dự án',
    'createNewPeriod': 'Tạo kỳ mới',
    'existingPeriods': 'Các kỳ hiện có',
    'noPeriodsYet': 'Chưa có kỳ nào được tạo',
    'projectCount': 'Dự án',
    'lastUpdated': 'Cập nhật lần cuối',
    'edit': 'Chỉnh sửa',
    'delete': 'Xóa',
    'editPeriod': 'Chỉnh sửa kỳ',
    'year': 'Năm',
    'half': 'Nửa kỳ',
    'searchProjects': 'Tìm kiếm dự án',
    'searchPlaceholder': 'Tìm theo tên, mã hoặc loại...',
    'projectsSelected': 'dự án đã chọn',
    'selectAll': 'Chọn tất cả',
    'deselectAll': 'Bỏ chọn tất cả',
    'noProjectsFound': 'Không tìm thấy dự án',
    'cancel': 'Hủy',
    'createPeriod': 'Tạo kỳ',
    'updatePeriod': 'Cập nhật kỳ',
    'pleaseSelectAtLeastOneProject': 'Vui lòng chọn ít nhất một dự án',
    'periodCreatedSuccessfully': 'Kỳ đã được tạo thành công',
    'periodAlreadyExists': 'Kỳ này đã tồn tại',
    'failedToCreatePeriod': 'Không thể tạo kỳ',
    'periodUpdatedSuccessfully': 'Kỳ đã được cập nhật thành công',
    'failedToUpdatePeriod': 'Không thể cập nhật kỳ',
    'confirmDeletePeriod': 'Bạn có chắc chắn muốn xóa kỳ ${period.label}? Điều này sẽ xóa tất cả phân công dự án.',
    'periodDeletedSuccessfully': 'Kỳ đã được xóa thành công',
    'failedToDeletePeriod': 'Không thể xóa kỳ',
    // Long-term Plan View
    'nav.longTermPlan': 'Kế hoạch dài hạn',
    'longTermPlan.title': 'Kế hoạch dài hạn kinh doanh OS',
    'longTermPlan.year': 'Năm',
    'longTermPlan.salesPlan': 'Kế hoạch doanh thu',
    'longTermPlan.salesActual': 'Doanh thu thực tế',
    'longTermPlan.hourlyRatePlan': 'Kế hoạch giá giờ TB',
    'longTermPlan.hourlyRateActual': 'Giá giờ TB thực tế',
    'longTermPlan.unit.sales': 'chục ngàn JPY',
    'longTermPlan.unit.hourlyRate': 'nghìn JPY/giờ',
    'longTermPlan.axis.year': 'Năm',
    'longTermPlan.axis.sales': 'Doanh thu (chục ngàn JPY)',
    'longTermPlan.axis.hourlyRate': 'Giá giờ TB (nghìn JPY/giờ)',
    'longTermPlan.legend.salesPlan': 'Kế hoạch doanh thu (chục ngàn JPY)',
    'longTermPlan.legend.salesActual': 'Doanh thu thực tế (chục ngàn JPY)',
    'longTermPlan.legend.hourlyRatePlan': 'Kế hoạch giá giờ TB',
    'longTermPlan.legend.hourlyRateActual': 'Giá giờ TB thực tế',
    'longTermPlan.copyToClipboard': 'Sao chép biểu đồ vào clipboard',
    'longTermPlan.exportPNG': 'Xuất dưới dạng ảnh PNG',
    'longTermPlan.exportSVG': 'Xuất dưới dạng SVG (vector, chất lượng tốt nhất)',
    'longTermPlan.exportData': 'Xuất dữ liệu biểu đồ dưới dạng CSV',
    'buttons.copy': 'Sao chép',
    // Monthly Plan-Actual View
    'nav.monthlyPlanActual': 'Kế hoạch-Thực tế tháng',
    'monthlyPlanActual.title': ' Kế hoạch-Thực tế kinh doanh OS hàng tháng',
    'monthlyPlanActual.subtitle': 'So sánh kế hoạch và thực tế hàng tháng',
    'monthlyPlanActual.capacityLine': 'Đường năng lực',
    'monthlyPlanActual.workingPlan': 'Kế hoạch giờ làm việc',
    'monthlyPlanActual.workingActual': 'Giờ làm việc thực tế',
    'monthlyPlanActual.salesPlan': 'Kế hoạch doanh thu',
    'monthlyPlanActual.salesActual': 'Doanh thu thực tế',
    'monthlyPlanActual.unit.sales': 'chục ngàn JPY',
    'monthlyPlanActual.unit.hours': 'giờ',
    'monthlyPlanActual.axis.sales': 'Doanh thu (chục ngàn JPY)',
    'monthlyPlanActual.axis.workingHours': 'Giờ làm việc hàng tháng (giờ)',
    'monthlyPlanActual.legend.capacityLine': 'Đường năng lực',
    'monthlyPlanActual.legend.workingPlan': 'Kế hoạch giờ làm việc',
    'monthlyPlanActual.legend.workingActual': 'Giờ làm việc thực tế',
    'monthlyPlanActual.legend.salesPlan': 'Kế hoạch doanh thu',
    'monthlyPlanActual.legend.salesActual': 'Doanh thu thực tế',
    'monthlyPlanActual.copyToClipboard': 'Sao chép biểu đồ vào clipboard',
    'monthlyPlanActual.exportPNG': 'Xuất dưới dạng ảnh PNG',
    'monthlyPlanActual.exportSVG': 'Xuất dưới dạng SVG (vector, chất lượng tốt nhất)',
    'monthlyPlanActual.exportData': 'Xuất dữ liệu biểu đồ dưới dạng CSV',
    'nav.catiaLicense': 'CATIAライセンス管理',
    'toast.saved': 'Đã lưu',
    'toast.saveFailed': 'Lưu thất bại',
    'toast.loadFailed': 'Không tải được dữ liệu',
    'toast.deleted': 'Đã xóa',
    'toast.deleteFailed': 'Xóa thất bại',
    'toast.exportDone': 'Xuất dữ liệu hoàn tất',
    'toast.exportFailed': 'Xuất dữ liệu thất bại',
    'toast.copied': 'Đã sao chép vào bộ nhớ tạm',
    'toast.copyFailed': 'Sao chép thất bại',
    'toast.codeFailed': 'Không tạo được mã dự án',
    'toast.nothingToSave': 'Không có thay đổi để lưu',
    'common.confirm': 'Xác nhận',
    'common.cancel': 'Hủy',
    'common.close': 'Đóng',
    'common.leave': 'Rời đi',
    'common.stay': 'Ở lại',
    'common.viewOnly': 'Chỉ xem',
    'common.loading': 'Đang tải…',
    'tracker.adminOnly': 'Chỉ quản trị viên mới được chỉnh sửa',
    'tracker.unsavedTitle': 'Có thay đổi chưa lưu',
    'tracker.unsavedLeaveConfirm': 'Bạn có thay đổi chưa lưu. Rời đi mà không lưu?',
    'tracker.savedCount': 'Đã lưu {count} thay đổi',
    'tracker.confirmDeleteProject': 'Xóa dự án này? Không thể hoàn tác.',
    'language.select': 'Chọn ngôn ngữ',
    'dashboard.noDataForYear': 'Không có dữ liệu cho năm {year}',
    'dashboard.licenseSyncing': 'Đang đồng bộ dữ liệu bản quyền…',
    'catia.syncing': 'Đang đồng bộ…',
    'catia.synced': 'Đã đồng bộ với máy chủ',
    'catia.syncError': 'Đồng bộ thất bại — đang hiển thị giá trị cục bộ',
    'catia.resetConfirm': 'Đặt lại toàn bộ giá trị bản quyền CATIA về mặc định?',
    'catia.title': 'Quản lý bản quyền CATIA',
    'catia.costTab': 'Chi phí bản quyền (vạn yên / tháng)',
    'catia.revenueTab': 'Doanh thu bản quyền (vạn yên / năm)',
    'catia.license': 'Bản quyền',
    'catia.resetDefaults': 'Đặt lại mặc định',
    'catia.subtitle': 'Theo dõi ROI và chi phí bản quyền tương tác',
    'catia.totalCostForYear': 'Tổng chi phí bản quyền năm {year}',
    'catia.infoEditable': 'Bảng này có thể tương tác — nhấp vào ô số bất kỳ để chỉnh sửa, giống như trong Excel.',
    'catia.infoAutoRecalc': 'Mọi thay đổi đều được lưu lên máy chủ và lập tức tính lại tổng chi phí năm {year} dùng cho biểu đồ Bảng điều khiển.',
    'catia.month': 'Tháng',
    'catia.purchase': 'Mua đứt',
    'catia.lease': 'Thuê',
    'catia.tipLabel': 'Mẹo',
    'catia.tipTooltip': 'Di chuột lên ô số để xem giá trị đầy đủ, chưa làm tròn trong chú giải.',
    'catia.tipEditable': 'Có thể cập nhật giá trị theo từng tháng ngay tại đây — không cần thay đổi mã nguồn.',
    'catia.manYenUnit': '万',
    'modals.project.planPrice': 'Đơn giá kế hoạch (JPY/giờ)',
    'modals.project.actualPrice': 'Đơn giá thực tế (JPY/giờ)',
    'modals.project.priceRequired': 'Vui lòng nhập đơn giá kế hoạch',
    'modals.project.created': 'Đã tạo dự án',
    'modals.project.createFailed': 'Tạo dự án thất bại',
    'editProject.saved': 'Đã cập nhật dự án',
    'editProject.saveFailed': 'Cập nhật dự án thất bại',
    'editProject.softwarePlaceholder': 'AutoCAD, Revit, v.v.',
    'editProject.softwareHint': 'Nhập nhiều tên phần mềm, phân tách bằng dấu phẩy hoặc xuống dòng.',
    'editProject.notesPlaceholder': 'Ghi chú...',
    'alerts.duplicatePeriod': 'Kỳ này đã tồn tại',
    'alerts.periodCreated': 'Đã tạo kỳ',
    'alerts.periodCreateFailed': 'Tạo kỳ thất bại',
    'alerts.projectsLoadFailed': 'Không tải được dự án',
    'periodManagement.selectProjects': 'Chọn ít nhất một dự án',
    'periodManagement.updated': 'Đã cập nhật kỳ',
    'periodManagement.updateFailed': 'Cập nhật kỳ thất bại',
    'periodManagement.deleted': 'Đã xóa kỳ',
    'periodManagement.deleteFailed': 'Xóa kỳ thất bại',
    'periodManagement.confirmDelete': 'Xóa kỳ này và dữ liệu liên quan?',
    'periodManagement.copied': 'Đã sao chép dự án',
    'periodManagement.copyFailed': 'Sao chép dự án thất bại',
    'common.edit': 'Chỉnh sửa',
    'common.delete': 'Xóa',
    'common.moveUp': 'Di chuyển lên',
    'common.moveDown': 'Di chuyển xuống',
    'common.save': 'Lưu thay đổi',
    'common.saving': 'Đang lưu...',
    'tracker.exclusion': 'Loại trừ',
    'totalView.tableHeader.price': 'Đơn giá',
    'details.planPrice': 'Đơn giá kế hoạch',
    'details.actualPrice': 'Đơn giá thực tế',
    'modal.editProject': 'Chỉnh sửa dự án',
    'dashboard.kpi.actualHoursDesc': 'Tổng thực tế năm',
    'dashboard.kpi.varianceLabel': 'Chênh lệch',
    'dashboard.net.plan.subtitle': 'Doanh thu kế hoạch - chi phí bản quyền',
    'dashboard.net.actual.subtitle': 'Doanh thu thực tế - chi phí bản quyền',
    'export.sections': 'Xuất phần này',
    'export.copyAsImage': 'Sao chép vào bộ nhớ tạm',
  }
};

/**
 * Module-level mirror of the active language, kept in sync by `LanguageProvider`.
 *
 * `translate()` exists for code that runs outside React and therefore cannot call
 * the `useLanguage()` hook — `utils/chartExport.ts` raises toasts from plain
 * functions. Components must keep using `useLanguage().t`, which re-renders on a
 * language change; `translate()` does not subscribe to anything.
 */
let activeLanguage: SupportedLanguage = readStoredLanguage();

export function translate(key: string, fallback?: string): string {
  return translations[activeLanguage][key] ?? translations.en[key] ?? fallback ?? key;
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<SupportedLanguage>(readStoredLanguage);

  useEffect(() => {
    activeLanguage = language;
    document.documentElement.lang = language;
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    } catch {
      // Persisting the language preference is best-effort only.
    }
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    toggleLanguage: () => setLanguage(prev => {
      const idx = LANGUAGE_ORDER.indexOf(prev);
      return LANGUAGE_ORDER[(idx + 1) % LANGUAGE_ORDER.length];
    }),
    t: (key: string, fallback?: string) => {
      return translations[language][key] ?? translations.en[key] ?? fallback ?? key;
    }
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
